name: system
description: The client side application for the system.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  common:
    path: ../common
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
