name: common
description: |
  A library of common classes, enums, and utililities to be shared across the client and server.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.2

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
